{
  "title": "CVE-2014-3730",
  "cve": "CVE-2014-3730",
  "notes": {
    "description": "The django.util.http.is_safe_url function in Django 1.4 before 1.4.13, 1.5 before 1.5.8, 1.6 before 1.6.5, and 1.7 before 1.7b4 does not properly validate URLs, which allows remote attackers to conduct open redirect attacks via a malformed URL, as demonstrated by \"http:\\\\\\djangoproject.com.\"",
    "published": "2014-05-16",
    "modified": "2017-01-04"
  },
  "references": [
    {
      "url": "http://www.securityfocus.com/bid/67410",
      "description": "BID:67410"
    },
    {
      "url": "https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/",
      "description": "CONFIRM:https://www.djangoproject.com/weblog/2014/may/14/security-releases-issued/"
    },
    {
      "url": "http://www.debian.org/security/2014/dsa-2934",
      "description": "DEBIAN:DSA-2934"
    },
    {
      "url": "http://www.openwall.com/lists/oss-security/2014/05/14/10",
      "description": "MLIST:[oss-security] 20140514 CVE Reuest: Django: Malformed URLs from user input incorrectly validated"
    },
    {
      "url": "http://www.openwall.com/lists/oss-security/2014/05/15/3",
      "description": "MLIST:[oss-security] 20140514 Re: CVE Reuest: Django: Malformed URLs from user input incorrectly validated"
    },
    {
      "url": "http://secunia.com/advisories/61281",
      "description": "SECUNIA:61281"
    },
    {
      "url": "http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html",
      "description": "SUSE:openSUSE-SU-2014:1132"
    },
    {
      "url": "http://ubuntu.com/usn/usn-2212-1",
      "description": "UBUNTU:USN-2212-1"
    }
  ]
}
