{
	"title": "CVE-2015-6817",
	"cve": "CVE-2015-6817",
	"notes": {
		"description": "PgBouncer 1.6.x before 1.6.1, when configured with auth_user, allows remote attackers to gain login access as auth_user via an unknown username.",
		"published": "2017-05-22",
		"modified": "2017-05-22"
	},
	"references": [
		{
			"url": "https://github.com/pgbouncer/pgbouncer/commit/7ca3e5279d05fceb1e8a043c6f5b6f58dea3ed38",
			"description": "CONFIRM:https://github.com/pgbouncer/pgbouncer/commit/7ca3e5279d05fceb1e8a043c6f5b6f58dea3ed38"
		},
		{
			"url": "https://github.com/pgbouncer/pgbouncer/issues/69",
			"description": "CONFIRM:https://github.com/pgbouncer/pgbouncer/issues/69"
		},
		{
			"url": "https://pgbouncer.github.io/2015/09/pgbouncer-1-6-1",
			"description": "CONFIRM:https://pgbouncer.github.io/2015/09/pgbouncer-1-6-1"
		},
		{
			"url": "https://security.gentoo.org/glsa/201701-24",
			"description": "GENTOO:GLSA-201701-24"
		},
		{
			"url": "http://comments.gmane.org/gmane.comp.db.postgresql.pgbouncer.general/1251",
			"description": "MISC:http://comments.gmane.org/gmane.comp.db.postgresql.pgbouncer.general/1251"
		},
		{
			"url": "http://www.openwall.com/lists/oss-security/2015/09/05/7",
			"description": "MLIST:[oss-security] 20150905 Re: CVE Request: PgBouncer: failed auth_query lookup leads to connection as auth_user"
		}
	]
}
