{
  "title": "CVE-2016-10149",
  "cve": "CVE-2016-10149",
  "notes": {
    "description": "XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response.",
    "published": "2017-03-24",
    "modified": "2018-01-04"
  },
  "references": [
    {
      "url": "http://www.securityfocus.com/bid/97692",
      "description": "BID:97692"
    },
    {
      "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716",
      "description": "CONFIRM:https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716"
    },
    {
      "url": "https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b",
      "description": "CONFIRM:https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b"
    },
    {
      "url": "https://github.com/rohe/pysaml2/pull/379",
      "description": "CONFIRM:https://github.com/rohe/pysaml2/pull/379"
    },
    {
      "url": "http://www.debian.org/security/2017/dsa-3759",
      "description": "DEBIAN:DSA-3759"
    },
    {
      "url": "https://github.com/rohe/pysaml2/issues/366",
      "description": "MISC:https://github.com/rohe/pysaml2/issues/366"
    },
    {
      "url": "http://www.openwall.com/lists/oss-security/2017/01/19/5",
      "description": "MLIST:[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack"
    },
    {
      "url": "https://access.redhat.com/errata/RHSA-2017:0936",
      "description": "REDHAT:RHSA-2017:0936"
    },
    {
      "url": "https://access.redhat.com/errata/RHSA-2017:0937",
      "description": "REDHAT:RHSA-2017:0937"
    },
    {
      "url": "https://access.redhat.com/errata/RHSA-2017:0938",
      "description": "REDHAT:RHSA-2017:0938"
    }
  ]
}
