{
	"title": "CVE-2020-15801",
	"cve": "CVE-2020-15801",
	"notes": {
		"description": "In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected.",
		"published": "2020-07-16",
		"modified": "2020-07-31"
	},
	"references": [
		{
			"url": "https://security.netapp.com/advisory/ntap-20200731-0003/",
			"description": "CONFIRM:https://security.netapp.com/advisory/ntap-20200731-0003/"
		},
		{
			"url": "https://bugs.python.org/issue41304",
			"description": "MISC:https://bugs.python.org/issue41304"
		},
		{
			"url": "https://github.com/python/cpython/pull/21495",
			"description": "MISC:https://github.com/python/cpython/pull/21495"
		}
	]
}
