{
	"title": "CVE-2022-42731",
	"cve": "CVE-2022-42731",
	"notes": [
		{
			"type": "Description",
			"text": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2022-10-11"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2022-10-11"
		}
	],
	"references": [
		{
			"url": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58",
			"description": "MISC:https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58"
		},
		{
			"url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release",
			"description": "MISC:https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release"
		},
		{
			"url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release",
			"description": "MISC:https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release"
		}
	]
}
