{
	"title": "CVE-2022-1289",
	"cve": "CVE-2022-1289",
	"notes": {
		"description": "A denial of service vulnerability was found in tildearrow Furnace. It has been classified as problematic. This is due to an incomplete fix of CVE-2022-1211. It is possible to initiate the attack remotely but it requires user interaction. The issue got fixed with the patch 0eb02422d5161767e9983bdaa5c429762d3477ce.",
		"published": "2022-04-10",
		"modified": "2022-04-10"
	},
	"references": [
		{
			"url": "https://github.com/tildearrow/furnace/commit/0eb02422d5161767e9983bdaa5c429762d3477ce",
			"description": "MISC:https://github.com/tildearrow/furnace/commit/0eb02422d5161767e9983bdaa5c429762d3477ce"
		},
		{
			"url": "https://github.com/tildearrow/furnace/issues/325#issuecomment-1094139655",
			"description": "MISC:https://github.com/tildearrow/furnace/issues/325#issuecomment-1094139655"
		},
		{
			"url": "https://vuldb.com/?id.196755",
			"description": "MISC:https://vuldb.com/?id.196755"
		}
	]
}
