{
	"title": "CVE-2021-3116",
	"cve": "CVE-2021-3116",
	"notes": [
		{
			"type": "Description",
			"text": "before_upstream_connection in AuthPlugin in http/proxy/auth.py in proxy.py before 2.3.1 accepts incorrect Proxy-Authorization header data because of a boolean confusion (and versus or)."
		},
		{
			"title": "Published",
			"type": "Other",
			"text": "2021-01-11"
		},
		{
			"title": "Modified",
			"type": "Other",
			"text": "2021-01-11"
		}
	],
	"references": [
		{
			"url": "https://cardaci.xyz/advisories/2021/01/10/proxy.py-2.3.0-broken-basic-authentication/",
			"description": "MISC:https://cardaci.xyz/advisories/2021/01/10/proxy.py-2.3.0-broken-basic-authentication/"
		},
		{
			"url": "https://github.com/abhinavsingh/proxy.py/pull/482/commits/9b00093288237f5073c403f2c4f62acfdfa8ed46",
			"description": "MISC:https://github.com/abhinavsingh/proxy.py/pull/482/commits/9b00093288237f5073c403f2c4f62acfdfa8ed46"
		},
		{
			"url": "https://pypi.org/project/proxy.py/2.3.1/#history",
			"description": "MISC:https://pypi.org/project/proxy.py/2.3.1/#history"
		}
	]
}
