{
  "title": "CVE-2013-4260",
  "cve": "CVE-2013-4260",
  "notes": {
    "description": "lib/ansible/playbook/__init__.py in Ansible 1.2.x before 1.2.3, when playbook does not run due to an error, allows local users to overwrite arbitrary files via a symlink attack on a retry file with a predictable name in /var/tmp/ansible/.",
    "published": "2013-09-16",
    "modified": "2023-02-12"
  },
  "references": [
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/86898",
      "description": "MISC:ansible-cve20134260-symlink(86898)"
    },
    {
      "url": "http://www.ansible.com/security",
      "description": "MISC:http://www.ansible.com/security"
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=998227",
      "description": "MISC:https://bugzilla.redhat.com/show_bug.cgi?id=998227"
    },
    {
      "url": "https://groups.google.com/forum/#%21topic/ansible-project/UVDYW0HGcNg",
      "description": "MISC:https://groups.google.com/forum/#%21topic/ansible-project/UVDYW0HGcNg"
    }
  ]
}
